package view;

import controller.DepartemenController;
import model.Departemen;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import view.MainMenu;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;

public class KelolaDepartemen extends javax.swing.JFrame {

    private DepartemenController departemenController;

    public KelolaDepartemen() {
        initComponents();
        departemenController = new DepartemenController();
        loadTableDepartemen();

        // Tambahkan listener untuk menangani klik pada tabel
        tblDepartemen.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                fillFormFromTable();
            }
        });
    }

    private void loadTableDepartemen() {
        DefaultTableModel model = (DefaultTableModel) tblDepartemen.getModel();
        model.setRowCount(0);

        List<Departemen> departemenList = departemenController.getAllDepartemen();
        for (Departemen departemen : departemenList) {
            Object[] row = {departemen.getIdDepartemen(), departemen.getNamaDepartemen()};
            model.addRow(row);
        }
    }

    private void fillFormFromTable() {
        int selectedRow = tblDepartemen.getSelectedRow();
        if (selectedRow >= 0) {
            // Ambil data dari tabel
            int idDepartemen = (int) tblDepartemen.getValueAt(selectedRow, 0);
            String namaDepartemen = (String) tblDepartemen.getValueAt(selectedRow, 1);

            // Isi data ke TextField
            txtIdDepartemen.setText(String.valueOf(idDepartemen));
            txtNamaDepartemen.setText(namaDepartemen);
        }
    }

    private void resetForm() {
        txtIdDepartemen.setText("");
        txtNamaDepartemen.setText("");
        tblDepartemen.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdDepartemen = new javax.swing.JTextField();
        txtNamaDepartemen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartemen = new javax.swing.JTable();
        btnResetDepartemen = new javax.swing.JButton();
        btnTambahDepartemen = new javax.swing.JButton();
        btnUbahDepartemen = new javax.swing.JButton();
        btnHapusDepartemen = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnReportDepartemen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("KELOLA DATA DEPARTEMEN");

        jLabel2.setText("ID Departemen");

        jLabel3.setText("Nama Departemen");

        txtIdDepartemen.setEditable(false);

        tblDepartemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Departemen", "Nama Departemen"
            }
        ));
        jScrollPane1.setViewportView(tblDepartemen);

        btnResetDepartemen.setText("Reset");
        btnResetDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDepartemenActionPerformed(evt);
            }
        });

        btnTambahDepartemen.setText("Tambah");
        btnTambahDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDepartemenActionPerformed(evt);
            }
        });

        btnUbahDepartemen.setText("Ubah");
        btnUbahDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDepartemenActionPerformed(evt);
            }
        });

        btnHapusDepartemen.setText("Hapus");
        btnHapusDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDepartemenActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnReportDepartemen.setText("Report");
        btnReportDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDepartemenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(151, 151, 151)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdDepartemen)
                                    .addComponent(txtNamaDepartemen, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 219, Short.MAX_VALUE)
                                .addComponent(btnTambahDepartemen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbahDepartemen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusDepartemen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetDepartemen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReportDepartemen))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetDepartemen)
                    .addComponent(btnTambahDepartemen)
                    .addComponent(btnUbahDepartemen)
                    .addComponent(btnHapusDepartemen)
                    .addComponent(btnKembali)
                    .addComponent(btnReportDepartemen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDepartemenActionPerformed
        try {
            String nama = txtNamaDepartemen.getText();

            Departemen departemen = new Departemen(0, nama);
            departemenController.addDepartemen(departemen);

            loadTableDepartemen();
            resetForm();

            // Notifikasi pop-up
            JOptionPane.showMessageDialog(this, "Data departemen berhasil ditambahkan!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahDepartemenActionPerformed

    private void btnUbahDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDepartemenActionPerformed
        try {
            int selectedRow = tblDepartemen.getSelectedRow();
            if (selectedRow >= 0) {
                int idDepartemen = Integer.parseInt(txtIdDepartemen.getText());
                String nama = txtNamaDepartemen.getText();

                Departemen departemen = new Departemen(idDepartemen, nama);
                departemenController.updateDepartemen(departemen);

                loadTableDepartemen();
                resetForm();

                // Notifikasi pop-up
                JOptionPane.showMessageDialog(this, "Data departemen berhasil diubah!",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUbahDepartemenActionPerformed

    private void btnHapusDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDepartemenActionPerformed
        try {
            int selectedRow = tblDepartemen.getSelectedRow();
            if (selectedRow >= 0) {
                int idDepartemen = (int) tblDepartemen.getValueAt(selectedRow, 0);

                departemenController.deleteDepartemen(idDepartemen);

                loadTableDepartemen();
                resetForm();

                // Notifikasi pop-up
                JOptionPane.showMessageDialog(this, "Data departemen berhasil dihapus!",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusDepartemenActionPerformed

    private void btnResetDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDepartemenActionPerformed
        txtNamaDepartemen.setText("");
    }//GEN-LAST:event_btnResetDepartemenActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnReportDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDepartemenActionPerformed
        try {
            // Lokasi file PDF
            String fileName = "Laporan_Departemen.pdf";

            // Membuat dokumen PDF
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(fileName));

            // Membuka dokumen
            document.open();

            // Menambahkan judul laporan
            document.add(new Paragraph("Laporan Data Departemen", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16)));
            document.add(new Paragraph(" "));

            // Membuat tabel PDF
            PdfPTable table = new PdfPTable(2); // 2 kolom
            table.setWidthPercentage(100);
            table.addCell("ID Departemen");
            table.addCell("Nama Departemen");

            // Ambil data dari tabel GUI
            DefaultTableModel model = (DefaultTableModel) tblDepartemen.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                table.addCell(model.getValueAt(i, 0).toString());
                table.addCell(model.getValueAt(i, 1).toString());
            }

            // Tambahkan tabel ke dokumen
            document.add(table);

            // Menutup dokumen
            document.close();

            // Notifikasi sukses
            JOptionPane.showMessageDialog(this, "Laporan berhasil disimpan di file " + fileName, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuat laporan!", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportDepartemenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaDepartemen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusDepartemen;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReportDepartemen;
    private javax.swing.JButton btnResetDepartemen;
    private javax.swing.JButton btnTambahDepartemen;
    private javax.swing.JButton btnUbahDepartemen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDepartemen;
    private javax.swing.JTextField txtIdDepartemen;
    private javax.swing.JTextField txtNamaDepartemen;
    // End of variables declaration//GEN-END:variables
}
